### ISSUE TITLE
Admin: Click to open quest

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-admin#2]
*Migrated to expeditionrpg/expedition#260 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Working with folders: https://developers.google.com/drive/v3/web/folder

To get parent folder: https://developers.google.com/drive/v3/reference/files/list

To add file to folder: https://developers.google.com/drive/v3/reference/files/update - addParent

Should test with authors@ address.

**Comment by toddmedema** [comment]
Note that you could also link to the drive file ID (which is the quest ID), and have people use the Open With -> Quest Creator menu. It's two extra clicks, but avoids a lot of dev & maintenance work: `https://drive.google.com/file/d/1nYsXfYjo1MzgIt2rrGWNe1QmxbsNVfS_/view`
